repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                .vscode/settings.json|
                src/frontend/.*|
                src/backend/server/app/alembic/.*
            )$
      - id: trailing-whitespace
        exclude: |
            (?x)^(
                src/frontend/.*|
                src/backend/server/app/alembic/.*
            )$
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: ["--config", "pyproject.toml", "--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format
        args: ["--config", "pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: false
        verbose: true
